
name: test lptest
on:
  push:
    branches:
      - master
jobs:
  build_job:
    name: generate new images
    runs-on: ubuntu-latest
    container:
      image: imagemagik:latest
      volumes:
        - ${{ github.workspace }}:/tmp
    steps:
      - name: Checkout website source
              id: checkout-master
              uses: actions/checkout@v2
      - name: convert img 02
              run: |
                convert lesspass_after.png \
                -draw 'fill yellow rectangle 50,70 453,105' \
                -fill black -pointsize ${fontsize_} -annotate +57+93 "${site_}" \
                -draw 'fill yellow rectangle 50,124 453,159' \
                -fill black -pointsize ${fontsize_} -annotate +57+147 "${username_}" \
                -draw 'fill yellow rectangle 50,178 363,213' \
                -fill red -pointsize ${fontsize_} -annotate +57+203 "< insert master password here >" \
                -draw 'fill yellow rectangle 48,336 116,364' \
                -fill black -pointsize $((fontsize_ - 2)) -annotate +55+357 "${length_}" \
                -strokewidth 4 \
                -fill "rgba( 0, 0, 0, 0 )" \
                -draw 'stroke yellow rectangle 20,390 455,428' \
                02.png

