
name: test lptest
on:
  push:
    branches: [ main ]
jobs:
  container_job:
    name: generate new images
    runs-on: ubuntu-latest
#    container:
#      image: imagemagik:latest
#      volumes:
#        - ${{ github.workspace }}:/tmp
    steps:

#      - uses: actions/checkout@main
      - uses: actions/checkout@v2

      - name: Check files
        run: ls -lart

      - run: sudo apt update ; sudo apt install imagemagick -y
#      - run: convert -version

#        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - run: source config.env

      - name: convert img 02
        run: |
                convert lesspass_after.png \
                -draw 'fill yellow rectangle 50,70 453,105' \
                -fill black -pointsize ${fontsize_} -annotate +57+93 "${site_}" \
                -draw 'fill yellow rectangle 50,124 453,159' \
                -fill black -pointsize ${fontsize_} -annotate +57+147 "${username_}" \
                -draw 'fill yellow rectangle 50,178 363,213' \
                -fill red -pointsize ${fontsize_} -annotate +57+203 "< insert master password here >" \
                -draw 'fill yellow rectangle 48,336 116,364' \
                -fill black -pointsize $((fontsize_ - 2)) -annotate +55+357 "${length_}" \
                -strokewidth 4 \
                -fill "rgba( 0, 0, 0, 0 )" \
                -draw 'stroke yellow rectangle 20,390 455,428' \
                docs/02.png

      - name: convert img 03
        run: |
                convert lesspass_after_2.png
                -draw 'fill yellow rectangle 50,70 453,105' \
                -fill black -pointsize ${fontsize_} -annotate +57+93 "${site_}" \
                -draw 'fill yellow rectangle 50,124 453,159' \
                -fill black -pointsize ${fontsize_} -annotate +57+147 "${username_}" \
                -draw 'fill yellow rectangle 48,336 116,364' \
                -fill black -pointsize $((fontsize_ - 2)) -annotate +55+357 "${length_}" \
                -strokewidth 4 \
                -fill "rgba( 0, 0, 0, 0 )" \
                -draw 'stroke yellow rectangle 20,390 455,428' \
                -strokewidth 2 \
                -fill "rgba( 255, 215, 0 , 0.9 )" \
                -draw 'stroke seagreen rectangle 63,391 371,426' \
                -fill green -pointsize ${fontsize_} -annotate +70+417 "< use this generated password >" \
                docs/03.png

      - run: |
                cat << EOF > docs/index.html
                <!DOCTYPE html>
                <html lang="en">
                  <head>
                    <title>lesspass test 1</title>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                  </head>
                  <body>

                    <h2>Steps to access ${app_} ...</h2>
                    <p>
                     assumes you have (should have been pre-shared with you):
                    <ul>
                     <li>${app_} has been installed</li>
                     <li>${app_} db  file: ${site_}.kdbx</li>
                     <li>${app_} key file: ${site_}.key</li>
                     <li>master password</li>
                    </ul>
                    </p>
                    <div>
                    <h3>1) goto <a href="https://www.lesspass.com" target="_blank" rel="noopener noreferrer">https://www.lesspass.com</a></h3>
                    <img width="${img_size_}" src="01.png" alt="01">
                    </div>
                    <br/>
                    <div>
                    <h3> 2) enter info into the form </h3>
                    <svg width="${svg_width_}" height="${svg_height_}" xmlns="http://www.w3.org/2000/svg">
                        <rect x="0" y="0" width="${svg_width_}" height="${svg_height_}" fill="aquamarine" />
                        <foreignobject x="0" y="0" width="${svg_width_}" height="${svg_height_}">
                            <body xmlns="http://www.w3.org/1999/xhtml">
                             <ul>
                               <li>Site: <b>${site_}</b></li>
                               <li>Username: <b>${username_}</b></li>
                               <li>Master Password: <b>**use your pre-shared master password**</b></li>
                               <li>Length: <b>${length_}</b></li>
                             </ul>
                            </body>
                        </foreignobject>
                    </svg>
                    <br/>
                    <img width="${img_size_}" src="02.png" alt="02">
                <div>
                    <u>note:</u> keep all other options at the defaults
                </div>
                <div>
                    when done - press <b>"Generate & Copy"</b>
                </div>
                    </div>
                    <br/>
                    <div>
                    <h3> 3) start "${app_}"</h3>
                    <ul>
                    <li>make sure both <b>${site_}.kdbx</b> and <b>${site_}.key</b> are in the same directory</li>
                    <li>then run: <b>${app_} ${site_}.kdbx</b> using the generated password as the ${app_} password</li>
                    </ul>
                    <img width="${img_size_}" src="03.png" alt="03">
                    </div>

                  </body>
                </html>
                EOF

