
name: test lptest
on:
  push:
    branches: [ main ]
jobs:
  container_job:
    name: generate new images
    runs-on: ubuntu-latest
#    container:
#      image: imagemagik:latest
#      volumes:
#        - ${{ github.workspace }}:/tmp
    steps:

#      - uses: actions/checkout@main
      - uses: actions/checkout@v2

      - name: Check files
        run: ls -lart

      - run: sudo apt update ; sudo apt install imagemagick -y
#      - run: convert -version

#        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - run: source runme.sh

