
name: test actions 1
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: generate new images
    runs-on: ubuntu-latest

#    container:
#      image: imagemagik:latest
#      volumes:
#        - ${{ github.workspace }}:/tmp

    steps:

#      - uses: actions/checkout@main
      - uses: actions/checkout@v2

      - name: Check files
        run: ls -lart

#      - run: sudo apt update ; sudo apt-get install -y -qq libvips ghostscript imagemagick
      - run: sudo apt-get install -y -qq libvips ghostscript imagemagick

#      - run: convert -version

      - name: Run a multi-line script
        shell: 'script -q -e -c "bash {0}"'
        run: source runme.sh

#       - name: Run a multi-line script
#         shell: 'script -q -e -c "bash {0}"'
#         run: |
#           perl -E 'say "Is STDOUT a TTY?: ", -t STDOUT ? "yes" : "no"'
#
# where shell: 'script -q -e -c "bash {0}"' is the trick.

#        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
